apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-store
  namespace: argocd
spec:
  destination:
    namespace: api-store
    server: https://kubernetes.default.svc
  project: laboratorio
  source:
    repoURL: "https://github.com/evandrogaguiar/api-store"
    targetRevision: main
    path: helm/api-store
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false