name: GitOps Helm Pipeline

on:
  push:
    branches:
      - main
env:
  ECR_REPOSITORY: api-store
  HELM_PATH: helm/api-store

jobs:
  build_image_and_update_helm_values:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Update values.yaml
        if: steps.build-image.conclusion == 'success'
        run: |
          cd ${{ env.HELM_PATH }}
          sed -i 's|tag:.*|tag: '${{ github.sha }}'|' values.yaml
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m 'Update values.yaml'
          git push
